[build]
  command = "pip install -r tiku/SmartQbank_Project/requirements.txt && flet publish tiku/SmartQbank_Project/main_desktop.py --output dist"
  publish = "dist"
[build.environment]
  PYTHON_VERSION = "3.10"
